### ISSUE TITLE
mOTUpan 

### ISSUE THREAD

**Issue by jnwoodhouse** [fpusan/SuperPang#8]
Hey guys, 

Naturally I went all in with 200 MAGs as a "test"

after 24 h  mOTUpan starts running and checks the checkm output

AssertionError: your completness files is badly formed, it should be TAB-separated (multispaced...) and needs a header line with 'Bin Id', 'Completeness', and 'Contamination' in it

-q/--checkm: CheckM output for the bins. This can be the STDOUT of running checkm on all the fasta files passed in --fasta, or a tab-delimited file in the form **genome1 percent_completeness**. If empty, completeness will be estimated by [mOTUpan](https://www.biorxiv.org/content/10.1101/2021.06.25.449606v1) but this may lead to wrong estimations for very incomplete genomes.

Obviously i provided the format specified in the help but mOTUpan says this is wrong. 

In any case maybe a check of the input files should occur at the start of the pipeline?

**Comment by fpusan** [comment]
Yes, currently I only check for the existence of the checkm file at the beginning of the run, not its format. Maybe there is a method in mOTUpan for checking this wihtout running the whole algorithm, I'll check with Moritz.

Still, if the format was ok it shouldn't have complained. Mind sharing your input data and the checkm file so I can try to reproduce?

**Comment by jnwoodhouse** [comment]
So the checkm file was as below (tab-delimiter)

I will add also contamination and the headers and rerun (with a subset) to see if that improves things

GROS21-1_SAMEA9560425_MAG_00000115.fa   87.16
GROS21-1_SAMEA9560440_MAG_00000050.fa   93.26
GROS21-1_SAMEA9560441_MAG_00000013.fa   92.06
GROS21-1_SAMEA9560442_MAG_00000034.fa   96.35
GROS21-1_SAMEA9560443_MAG_00000073.fa   95.76
GROS21-1_SAMEA9560444_MAG_00000014.fa   95.98
GROS21-1_SAMEA9560445_MAG_00000021.fa   95.33
GROS21-1_SAMEA9560446_MAG_00000011.fa   94.72
GROS21-1_SAMEA9560447_MAG_00000021.fa   71.97
GROS21-1_SAMEA9560451_MAG_00000038.fa   95.88

**Comment by fpusan** [comment]
Yeah, you probably need to remove the extension `.fa`  from the genome names since checkm doesn't output the extension. I definitely need to clarify this in the documentation.
You don't really need the contamination or other info. Check with the subset, hopefully it'll work.
Also, 24 hours running time is a bit too much (but not impossible, I guess) . May I ask how large are the MAGs on average, and what is their minimum ANI? And the number of threads you used.

**Comment by fpusan** [comment]
Hopefully fixed, now we check the completeness file before doing all the heavy lifting.
I also made the documentation more clear. Actually, my previous post about not needing the contamination was a half-lie... you don't need it, as long as the extension of your file is `tsv`. Otherwise mOTUlizer's parser is triggered, and that one expects either STOUT from checkm or a tab-separated file with headers and `genome completeness contamination`...
Anyways it should be clear now.
