### ISSUE TITLE
errors when running the test-SuperPang.py

### ISSUE THREAD

**Issue by liushanlin** [fpusan/SuperPang#9]
the error message is as follows:

Reconstructing contigs
  File "/home/sl/.conda/envs/SuperPang/bin/condense-edges.py", line 254, in <module>
    main()
  File "/home/sl/.conda/envs/SuperPang/bin/condense-edges.py", line 60, in main
    GS.add_edge_list(edges)
  File "/home/sl/.conda/envs/SuperPang/lib/python3.8/site-packages/graph_tool/__init__.py", line 2603, in add_edge_list
    libcore.add_edge_list_iter(self.__graph, edge_list, eprops)
TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type Vertex

There was an error running condense-edges.py.

**Comment by fpusan** [comment]
Thanks for trying SuperPang
May I ask what is your operating system and distribution?
Did the first part of the pipeline (before condense edges) run correctly?

**Comment by fpusan** [comment]
Nevermind, could reproduce the issue in my computer.

Turns out that they released a new update of graph-tool in anaconda cloud yesterday, and it somehow breaks that piece of code.
For now, you can revert to the old graph-tool version by typing `conda install -c conda-forge graph-tool=2.45` when inside your SuperPang environment. This fixed the issue for me.

Tomorrow I will work on a more permanent solution and make a new release when get everything sorted out.

Thanks for reporting!

**Comment by liushanlin** [comment]
It works. Thanks for the quick reply.

**Comment by fpusan** [comment]
I just released a new version including a fix for the issue
